# Generated by Django 2.1.3 on 2019-02-23 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingedient',
            name='recepie_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cook.Recipie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingedient',
            name='name',
            field=models.TextField(),
        ),
    ]
