# Generated by Django 2.1.3 on 2019-02-23 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0002_auto_20190223_2220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingedient',
            new_name='Ingredient',
        ),
    ]
