# Generated by Django 2.1.3 on 2019-02-23 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0003_auto_20190223_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepieIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='recepie_id',
        ),
        migrations.AlterField(
            model_name='recipie',
            name='image',
            field=models.ImageField(upload_to='recepies/<django.db.models.fields.TextField>'),
        ),
        migrations.AddField(
            model_name='recepieingredients',
            name='ingredient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Ingredient'),
        ),
        migrations.AddField(
            model_name='recepieingredients',
            name='recepie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Recipie'),
        ),
    ]
