# Generated by Django 2.1.3 on 2019-02-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0004_auto_20190223_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepieingredients',
            name='ingredient_id',
        ),
        migrations.RemoveField(
            model_name='recepieingredients',
            name='recepie_id',
        ),
        migrations.AddField(
            model_name='recipie',
            name='ingredients',
            field=models.ManyToManyField(to='cook.Ingredient'),
        ),
        migrations.DeleteModel(
            name='RecepieIngredients',
        ),
    ]
