# Generated by Django 2.1.3 on 2019-03-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0006_auto_20190224_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.TextField(default='No category'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='data',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.TextField(default='No description'),
        ),
    ]
